import Foundation
extension Notification.Name{
    static let LibaryWallpaper = Notification.Name("Downloading")
   static let ClickLoadpercent_wallpaperHome = Notification.Name("ClickLoadpercent_wallpaperHome")
    static let SeeallLoadpercent_wallpaperHome = Notification.Name("SeeallLoadpercent_wallpaperHome")
    static let LiveDownload = Notification.Name("Downloading")
    static let CategoriesDownload = Notification.Name("Downloading")
    static let Library = Notification.Name("Downloading")
    static let Loadpercent_wallpaperHome = Notification.Name("loadpercent_WallpaperHome")
    static let LiveCate = Notification.Name("downloading")
    static let NewArrival_SeeAll = Notification.Name("downloading")
    static let Poplular = Notification.Name("downloading")
    static let Loadpercent_livewallpaperHome = Notification.Name("Loadpercent_livewallpaperHome")
    static let initLive = Notification.Name("initLive")
    static let Popular_SeeAll = Notification.Name("Popular_SeeAll")
    static let Wallpapers_Screen = Notification.Name("Wallpapers_Screen")
    static let Live_Screen = Notification.Name("Live_Screen")
    static let hideChup = Notification.Name("hideChup")
    static let showChup = Notification.Name("showChup")
    static let SeeallLoadpercent_livewallpaperHome = Notification.Name("SeeallLoadpercent_livewallpaperHome")
    static let SeeallinitLive = Notification.Name("SeeallinitLive")
    static let CSeeallLoadpercent_livewallpaperHome = Notification.Name("CSeeallLoadpercent_livewallpaperHome")
    static let CSeeallinitLive = Notification.Name("CSeeallinitLive")
    static let SaveSCHome = Notification.Name("SaveSCHome")
    static let CSaveSCHome = Notification.Name("CSaveSCHome")
    static let reloadLiveWallpapers = Notification.Name("reloadLiveWallpapers")
    static let SaveSCMy = Notification.Name("SaveSCMy")
    static let CSaveSCClick = Notification.Name("CSaveSCClick")
    static let SWHome = Notification.Name("SWHome")
    static let SWClick = Notification.Name("SWClick")
    static let SLHome = Notification.Name("SLHome")
    static let SLClick = Notification.Name("SLClick")
}
